package com.advantage.RaiffeisenBank;

import com.thinkdesquared.banking.LoginActivity;
import com.thinkdesquared.banking.choosers.ChoosePinCodeKeyboardFragment;
import com.thinkdesquared.banking.choosers.templates.events.ManageTemplatesResponseEvent;
import com.thinkdesquared.banking.choosers.templates.events.TemplateClickedEvent;
import com.thinkdesquared.banking.choosers.templates.presenter.TemplatesChooserPresenter;
import com.thinkdesquared.banking.core.view.LogoutActivity;
import com.thinkdesquared.banking.events.CancelPinKeyboardEvent;
import com.thinkdesquared.banking.events.ChangeUserPinCodeEvent;
import com.thinkdesquared.banking.events.ChoosePinCodeChangedEvent;
import com.thinkdesquared.banking.events.ClearChoosePinCodeChangedEvent;
import com.thinkdesquared.banking.events.DateButtonCallBackEvent;
import com.thinkdesquared.banking.events.DatePickerFragmentShouldReturnEvent;
import com.thinkdesquared.banking.events.LogoutFinishedEvent;
import com.thinkdesquared.banking.events.ValidateRememberMeLoginPINResponseEvent;
import com.thinkdesquared.banking.events.WidgetConfigurationEvent;
import com.thinkdesquared.banking.events.WidgetSelectEvent;
import com.thinkdesquared.banking.money.mandates.CreateMandateActivity;
import com.thinkdesquared.banking.money.mandates.CreateMandateVerifyFragment;
import com.thinkdesquared.banking.money.mandates.DeleteMandateVerifyFragment;
import com.thinkdesquared.banking.money.mandates.MandateListFiltersContainerActivity;
import com.thinkdesquared.banking.money.mandates.ModifyMandateVerifyFragment;
import com.thinkdesquared.banking.money.mandates.RejectMandateVerifyFragment;
import com.thinkdesquared.banking.money.mandates.events.ChooseSuppliersButtonClickedEvent;
import com.thinkdesquared.banking.money.mandates.events.CreateMandateInputResponseEvent;
import com.thinkdesquared.banking.money.mandates.events.CreateMandateResultResponseEvent;
import com.thinkdesquared.banking.money.mandates.events.CreateMandateVerifyEvent;
import com.thinkdesquared.banking.money.mandates.events.CreateMandateVerifyResponseEvent;
import com.thinkdesquared.banking.money.mandates.events.CustomerIdentifierResponseEvent;
import com.thinkdesquared.banking.money.mandates.events.DeleteMandateResultResponseEvent;
import com.thinkdesquared.banking.money.mandates.events.DeleteMandateVerifyResponseEvent;
import com.thinkdesquared.banking.money.mandates.events.EligibleSuppliersResponseEvent;
import com.thinkdesquared.banking.money.mandates.events.GetMandatesResponseEvent;
import com.thinkdesquared.banking.money.mandates.events.MandateActionButtonClickedEvent;
import com.thinkdesquared.banking.money.mandates.events.MandateFiltersDiscardChangesEvent;
import com.thinkdesquared.banking.money.mandates.events.MandateListFiltersAppliedEvent;
import com.thinkdesquared.banking.money.mandates.events.ModifyMandateInputResponseEvent;
import com.thinkdesquared.banking.money.mandates.events.ModifyMandateResultResponseEvent;
import com.thinkdesquared.banking.money.mandates.events.ModifyMandateVerifyEvent;
import com.thinkdesquared.banking.money.mandates.events.ModifyMandateVerifyResponseEvent;
import com.thinkdesquared.banking.money.mandates.events.RejectMandateResultResponseEvent;
import com.thinkdesquared.banking.money.mandates.events.RejectMandateVerifyResponseEvent;
import com.thinkdesquared.banking.money.mandates.events.SupplierInfoResponseEvent;
import com.thinkdesquared.banking.money.mandates.events.ViewMandateResponseEvent;
import com.thinkdesquared.banking.money.mandates.presenter.CreateMandatePresenter;
import com.thinkdesquared.banking.money.mandates.presenter.ListMandatesPresenter;
import com.thinkdesquared.banking.money.mandates.presenter.ModifyMandatePresenter;
import com.thinkdesquared.banking.money.mandates.presenter.ViewMandatePresenter;
import com.thinkdesquared.banking.rememberme.RememberMeLoginActivity;
import com.thinkdesquared.banking.rememberme.RememberMeLoginFragment;
import com.thinkdesquared.banking.services.ManageDeviceChangePinActivity;
import com.thinkdesquared.banking.services.ManageDevicesActivity;
import com.thinkdesquared.banking.services.ManageDevicesShowDeviceFragment;
import com.thinkdesquared.banking.services.securemessages.events.CreateSecureMessageInputServiceResponseEvent;
import com.thinkdesquared.banking.services.securemessages.events.DeleteSecureMessageResponseEvent;
import com.thinkdesquared.banking.services.securemessages.events.DownloadBitmapResponseEvent;
import com.thinkdesquared.banking.services.securemessages.events.GetConversationSecureMessagesResponseEvent;
import com.thinkdesquared.banking.services.securemessages.events.GetSecureMessageAttachmentResponseEvent;
import com.thinkdesquared.banking.services.securemessages.events.GetSecureMessageConversationsResponseEvent;
import com.thinkdesquared.banking.services.securemessages.events.GetSecureMessageEmbeddedImageResponseEvent;
import com.thinkdesquared.banking.services.securemessages.events.InboxActionButtonClickedEvent;
import com.thinkdesquared.banking.services.securemessages.events.InboxFiltersPerformSearchEvent;
import com.thinkdesquared.banking.services.securemessages.events.InvalidateInboxListEvent;
import com.thinkdesquared.banking.services.securemessages.events.SecureMessagesLoadingStateChangedEvent;
import com.thinkdesquared.banking.services.securemessages.events.SendSecureMessageEvent;
import com.thinkdesquared.banking.services.securemessages.helpers.EmbeddedImagesDownloader;
import com.thinkdesquared.banking.services.securemessages.presenter.SecureMessageComposePresenter;
import com.thinkdesquared.banking.services.securemessages.presenter.SecureMessageInboxFiltersPresenter;
import com.thinkdesquared.banking.services.securemessages.presenter.SecureMessageInboxPresenter;
import com.thinkdesquared.banking.services.securemessages.presenter.SecureMessageInboxViewMessagePresenter;
import com.thinkdesquared.banking.services.securemessages.presenter.SecureMessageReplyPresenter;
import com.thinkdesquared.banking.services.widget.ManageDeviceInformationFragment;
import com.thinkdesquared.banking.transfers.events.ExecuteUpdateTouchIdAuthorizationResponseEvent;
import com.thinkdesquared.banking.transfers.mobiletopup.MobileTopUpActivity;
import com.thinkdesquared.banking.transfers.mobiletopup.MobileTopUpVerifyFragment;
import com.thinkdesquared.banking.transfers.mobiletopup.events.CalculateConvertedAmountWithBookRateResponseEvent;
import com.thinkdesquared.banking.transfers.mobiletopup.events.MobileTopUpInputResponseEvent;
import com.thinkdesquared.banking.transfers.mobiletopup.events.MobileTopUpResultResponseEvent;
import com.thinkdesquared.banking.transfers.mobiletopup.events.MobileTopUpVerifyEvent;
import com.thinkdesquared.banking.transfers.mobiletopup.events.MobileTopUpVerifyResponseEvent;
import com.thinkdesquared.banking.transfers.mobiletopup.presenter.MobileTopUpPresenter;
import com.thinkdesquared.banking.transfers.payments.IntrabankPaymentFragment;
import com.thinkdesquared.banking.transfers.payments.PaymentVerifyFragment;
import com.thinkdesquared.banking.transfers.payments.PaymentsActivity;
import com.thinkdesquared.banking.transfers.payments.events.OnAddClickEvent;
import com.thinkdesquared.banking.transfers.payments.events.PaymentGenericResultResponseEvent;
import com.thinkdesquared.banking.transfers.payments.events.PaymentVerifyEvent;
import com.thinkdesquared.banking.transfers.payments.events.PaymentVerifyResponseEvent;
import com.thinkdesquared.banking.transfers.payments.events.PaymentsInputResponseEvent;
import com.thinkdesquared.banking.transfers.payments.events.ValidateAccountResponseEvent;
import com.thinkdesquared.banking.transfers.payments.events.ValidateDisplayStatisticalCodeResponseEvent;
import com.thinkdesquared.banking.transfers.payments.events.ValidateSEPAResponseEvent;
import com.thinkdesquared.banking.transfers.payments.presenter.DomesticPaymentPresenter;
import com.thinkdesquared.banking.transfers.payments.presenter.InternationalPaymentPresenter;
import com.thinkdesquared.banking.transfers.payments.presenter.IntrabankPaymentPresenter;
import com.thinkdesquared.banking.transfers.payments.presenter.PaymentsPresenter;
import com.thinkdesquared.banking.transfers.treasury.CreateTreasuryActivity;
import com.thinkdesquared.banking.transfers.treasury.CreateTreasuryVerifyFragment;
import com.thinkdesquared.banking.transfers.treasury.DeleteTreasuryVerifyFragment;
import com.thinkdesquared.banking.transfers.treasury.events.CreateTreasuryInputResponseEvent;
import com.thinkdesquared.banking.transfers.treasury.events.CreateTreasuryResultResponseEvent;
import com.thinkdesquared.banking.transfers.treasury.events.CreateTreasuryVerifyEvent;
import com.thinkdesquared.banking.transfers.treasury.events.CreateTreasuryVerifyResponseEvent;
import com.thinkdesquared.banking.transfers.treasury.events.DeleteTreasuryResultResponseEvent;
import com.thinkdesquared.banking.transfers.treasury.events.DeleteTreasuryVerifyResponseEvent;
import com.thinkdesquared.banking.transfers.treasury.events.GetTreasuryBeneficiariesResponseEvent;
import com.thinkdesquared.banking.transfers.treasury.events.ValidateTreasuryCNPResponseEvent;
import com.thinkdesquared.banking.transfers.treasury.presenter.CreateTreasuryPresenter;
import com.thinkdesquared.banking.widget.RZBAppWidgetConfigurationActivity;
import com.thinkdesquared.banking.widget.actions.WidgetHelper;
import com.thinkdesquared.banking.widget.events.LogoutWidgetEvent;
import com.thinkdesquared.banking.widget.events.StopWidgetServiceEvent;
import com.thinkdesquared.banking.widget.services.WidgetGetDataService;
import java.util.HashMap;
import java.util.Map;
import org.greenrobot.eventbus.ThreadMode;
import org.greenrobot.eventbus.meta.SimpleSubscriberInfo;
import org.greenrobot.eventbus.meta.SubscriberInfo;
import org.greenrobot.eventbus.meta.SubscriberInfoIndex;
import org.greenrobot.eventbus.meta.SubscriberMethodInfo;

public class EventBusIndex
  implements SubscriberInfoIndex
{
  private static final Map<Class<?>, SubscriberInfo> SUBSCRIBER_INDEX = new HashMap();
  
  static
  {
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo1 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo1[0] = new SubscriberMethodInfo("onEvent", LogoutFinishedEvent.class, ThreadMode.POSTING, 0, true);
    putIndex(new SimpleSubscriberInfo(LogoutActivity.class, true, arrayOfSubscriberMethodInfo1));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo2 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo2[0] = new SubscriberMethodInfo("onEventMainThread", MobileTopUpVerifyResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo2[1] = new SubscriberMethodInfo("onEventMainThread", MobileTopUpResultResponseEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(MobileTopUpVerifyFragment.class, true, arrayOfSubscriberMethodInfo2));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo3 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo3[0] = new SubscriberMethodInfo("onEvent", WidgetSelectEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo3[1] = new SubscriberMethodInfo("onEvent", WidgetConfigurationEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(RZBAppWidgetConfigurationActivity.class, true, arrayOfSubscriberMethodInfo3));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo4 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo4[0] = new SubscriberMethodInfo("onEvent", GetMandatesResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo4[1] = new SubscriberMethodInfo("onEvent", MandateActionButtonClickedEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(ListMandatesPresenter.class, true, arrayOfSubscriberMethodInfo4));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo5 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo5[0] = new SubscriberMethodInfo("onEvent", ValidateAccountResponseEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(IntrabankPaymentPresenter.class, true, arrayOfSubscriberMethodInfo5));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo6 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo6[0] = new SubscriberMethodInfo("onEvent", ModifyMandateVerifyResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo6[1] = new SubscriberMethodInfo("onEvent", ModifyMandateResultResponseEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(ModifyMandateVerifyFragment.class, true, arrayOfSubscriberMethodInfo6));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo7 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo7[0] = new SubscriberMethodInfo("onEvent", ChoosePinCodeChangedEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo7[1] = new SubscriberMethodInfo("onEvent", ValidateRememberMeLoginPINResponseEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(ManageDevicesShowDeviceFragment.class, true, arrayOfSubscriberMethodInfo7));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo8 = new SubscriberMethodInfo[6];
    arrayOfSubscriberMethodInfo8[0] = new SubscriberMethodInfo("onEvent", GetSecureMessageConversationsResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo8[1] = new SubscriberMethodInfo("onEvent", InboxActionButtonClickedEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo8[2] = new SubscriberMethodInfo("onEvent", CreateSecureMessageInputServiceResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo8[3] = new SubscriberMethodInfo("onEvent", DeleteSecureMessageResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo8[4] = new SubscriberMethodInfo("onEvent", InboxFiltersPerformSearchEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo8[5] = new SubscriberMethodInfo("onEvent", InvalidateInboxListEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(SecureMessageInboxPresenter.class, true, arrayOfSubscriberMethodInfo8));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo9 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo9[0] = new SubscriberMethodInfo("onEventMainThread", PaymentsInputResponseEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(PaymentsPresenter.class, true, arrayOfSubscriberMethodInfo9));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo10 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo10[0] = new SubscriberMethodInfo("onEvent", DeleteMandateVerifyResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo10[1] = new SubscriberMethodInfo("onEvent", DeleteMandateResultResponseEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(DeleteMandateVerifyFragment.class, true, arrayOfSubscriberMethodInfo10));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo11 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo11[0] = new SubscriberMethodInfo("onEvent", ExecuteUpdateTouchIdAuthorizationResponseEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(RememberMeLoginActivity.class, true, arrayOfSubscriberMethodInfo11));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo12 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo12[0] = new SubscriberMethodInfo("onEventMainThread", PaymentsInputResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo12[1] = new SubscriberMethodInfo("onEvent", ValidateAccountResponseEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(DomesticPaymentPresenter.class, true, arrayOfSubscriberMethodInfo12));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo13 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo13[0] = new SubscriberMethodInfo("onEvent", ChoosePinCodeChangedEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo13[1] = new SubscriberMethodInfo("onEvent", CancelPinKeyboardEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(ManageDeviceChangePinActivity.class, true, arrayOfSubscriberMethodInfo13));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo14 = new SubscriberMethodInfo[3];
    arrayOfSubscriberMethodInfo14[0] = new SubscriberMethodInfo("onEvent", DateButtonCallBackEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo14[1] = new SubscriberMethodInfo("onEvent", DatePickerFragmentShouldReturnEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo14[2] = new SubscriberMethodInfo("onEventMainThread", CreateTreasuryVerifyEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(CreateTreasuryActivity.class, true, arrayOfSubscriberMethodInfo14));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo15 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo15[0] = new SubscriberMethodInfo("onEvent", SecureMessagesLoadingStateChangedEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo15[1] = new SubscriberMethodInfo("onEvent", DateButtonCallBackEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(SecureMessageInboxFiltersPresenter.class, true, arrayOfSubscriberMethodInfo15));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo16 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo16[0] = new SubscriberMethodInfo("onEventMainThread", CreateTreasuryVerifyResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo16[1] = new SubscriberMethodInfo("onEventMainThread", CreateTreasuryResultResponseEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(CreateTreasuryVerifyFragment.class, true, arrayOfSubscriberMethodInfo16));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo17 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo17[0] = new SubscriberMethodInfo("onEvent", LogoutWidgetEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(WidgetHelper.class, true, arrayOfSubscriberMethodInfo17));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo18 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo18[0] = new SubscriberMethodInfo("onEvent", ChoosePinCodeChangedEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo18[1] = new SubscriberMethodInfo("onEvent", CancelPinKeyboardEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(RememberMeLoginFragment.class, true, arrayOfSubscriberMethodInfo18));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo19 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo19[0] = new SubscriberMethodInfo("onEvent", OnAddClickEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(IntrabankPaymentFragment.class, true, arrayOfSubscriberMethodInfo19));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo20 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo20[0] = new SubscriberMethodInfo("onEvent", ExecuteUpdateTouchIdAuthorizationResponseEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(LoginActivity.class, true, arrayOfSubscriberMethodInfo20));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo21 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo21[0] = new SubscriberMethodInfo("onEvent", RejectMandateVerifyResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo21[1] = new SubscriberMethodInfo("onEvent", RejectMandateResultResponseEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(RejectMandateVerifyFragment.class, true, arrayOfSubscriberMethodInfo21));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo22 = new SubscriberMethodInfo[3];
    arrayOfSubscriberMethodInfo22[0] = new SubscriberMethodInfo("onEvent", GetConversationSecureMessagesResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo22[1] = new SubscriberMethodInfo("onEvent", GetSecureMessageAttachmentResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo22[2] = new SubscriberMethodInfo("onEvent", DeleteSecureMessageResponseEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(SecureMessageReplyPresenter.class, true, arrayOfSubscriberMethodInfo22));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo23 = new SubscriberMethodInfo[4];
    arrayOfSubscriberMethodInfo23[0] = new SubscriberMethodInfo("onEvent", CreateMandateInputResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo23[1] = new SubscriberMethodInfo("onEvent", EligibleSuppliersResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo23[2] = new SubscriberMethodInfo("onEvent", SupplierInfoResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo23[3] = new SubscriberMethodInfo("onEvent", CustomerIdentifierResponseEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(CreateMandatePresenter.class, true, arrayOfSubscriberMethodInfo23));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo24 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo24[0] = new SubscriberMethodInfo("onEvent", ViewMandateResponseEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(ViewMandatePresenter.class, true, arrayOfSubscriberMethodInfo24));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo25 = new SubscriberMethodInfo[4];
    arrayOfSubscriberMethodInfo25[0] = new SubscriberMethodInfo("onEvent", DateButtonCallBackEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo25[1] = new SubscriberMethodInfo("onEvent", DatePickerFragmentShouldReturnEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo25[2] = new SubscriberMethodInfo("onEvent", CreateMandateVerifyEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo25[3] = new SubscriberMethodInfo("onEvent", ModifyMandateVerifyEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(CreateMandateActivity.class, true, arrayOfSubscriberMethodInfo25));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo26 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo26[0] = new SubscriberMethodInfo("onEvent", ChoosePinCodeChangedEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(ManageDeviceInformationFragment.class, true, arrayOfSubscriberMethodInfo26));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo27 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo27[0] = new SubscriberMethodInfo("onEventMainThread", DeleteTreasuryVerifyResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo27[1] = new SubscriberMethodInfo("onEventMainThread", DeleteTreasuryResultResponseEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(DeleteTreasuryVerifyFragment.class, true, arrayOfSubscriberMethodInfo27));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo28 = new SubscriberMethodInfo[3];
    arrayOfSubscriberMethodInfo28[0] = new SubscriberMethodInfo("onEvent", MandateFiltersDiscardChangesEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo28[1] = new SubscriberMethodInfo("onEvent", ChooseSuppliersButtonClickedEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo28[2] = new SubscriberMethodInfo("onEvent", MandateListFiltersAppliedEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(MandateListFiltersContainerActivity.class, true, arrayOfSubscriberMethodInfo28));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo29 = new SubscriberMethodInfo[6];
    arrayOfSubscriberMethodInfo29[0] = new SubscriberMethodInfo("onEvent", GetConversationSecureMessagesResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo29[1] = new SubscriberMethodInfo("onEvent", DeleteSecureMessageResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo29[2] = new SubscriberMethodInfo("onEvent", GetSecureMessageAttachmentResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo29[3] = new SubscriberMethodInfo("onEvent", CreateSecureMessageInputServiceResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo29[4] = new SubscriberMethodInfo("onEvent", InvalidateInboxListEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo29[5] = new SubscriberMethodInfo("onEvent", InboxFiltersPerformSearchEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(SecureMessageInboxViewMessagePresenter.class, true, arrayOfSubscriberMethodInfo29));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo30 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo30[0] = new SubscriberMethodInfo("onEvent", SendSecureMessageEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(SecureMessageComposePresenter.class, true, arrayOfSubscriberMethodInfo30));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo31 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo31[0] = new SubscriberMethodInfo("onEvent", StopWidgetServiceEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(WidgetGetDataService.class, true, arrayOfSubscriberMethodInfo31));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo32 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo32[0] = new SubscriberMethodInfo("onEventMainThread", ManageTemplatesResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo32[1] = new SubscriberMethodInfo("onEventMainThread", TemplateClickedEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(TemplatesChooserPresenter.class, true, arrayOfSubscriberMethodInfo32));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo33 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo33[0] = new SubscriberMethodInfo("onEventMainThread", DownloadBitmapResponseEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(ManageDevicesActivity.class, true, arrayOfSubscriberMethodInfo33));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo34 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo34[0] = new SubscriberMethodInfo("onEventMainThread", MobileTopUpInputResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo34[1] = new SubscriberMethodInfo("onEventMainThread", CalculateConvertedAmountWithBookRateResponseEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(MobileTopUpPresenter.class, true, arrayOfSubscriberMethodInfo34));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo35 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo35[0] = new SubscriberMethodInfo("onEventMainThread", PaymentVerifyResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo35[1] = new SubscriberMethodInfo("onEventMainThread", PaymentGenericResultResponseEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(PaymentVerifyFragment.class, true, arrayOfSubscriberMethodInfo35));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo36 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo36[0] = new SubscriberMethodInfo("onEvent", ModifyMandateInputResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo36[1] = new SubscriberMethodInfo("onEvent", CustomerIdentifierResponseEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(ModifyMandatePresenter.class, true, arrayOfSubscriberMethodInfo36));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo37 = new SubscriberMethodInfo[3];
    arrayOfSubscriberMethodInfo37[0] = new SubscriberMethodInfo("onEvent", DateButtonCallBackEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo37[1] = new SubscriberMethodInfo("onEvent", DatePickerFragmentShouldReturnEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo37[2] = new SubscriberMethodInfo("onEvent", PaymentVerifyEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(PaymentsActivity.class, true, arrayOfSubscriberMethodInfo37));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo38 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo38[0] = new SubscriberMethodInfo("onEvent", ValidateSEPAResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo38[1] = new SubscriberMethodInfo("onEvent", ValidateDisplayStatisticalCodeResponseEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(InternationalPaymentPresenter.class, true, arrayOfSubscriberMethodInfo38));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo39 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo39[0] = new SubscriberMethodInfo("onEvent", GetSecureMessageEmbeddedImageResponseEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(EmbeddedImagesDownloader.class, true, arrayOfSubscriberMethodInfo39));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo40 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo40[0] = new SubscriberMethodInfo("onEvent", CreateMandateVerifyResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo40[1] = new SubscriberMethodInfo("onEvent", CreateMandateResultResponseEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(CreateMandateVerifyFragment.class, true, arrayOfSubscriberMethodInfo40));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo41 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo41[0] = new SubscriberMethodInfo("onEvent", ChangeUserPinCodeEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo41[1] = new SubscriberMethodInfo("onEvent", ClearChoosePinCodeChangedEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(ChoosePinCodeKeyboardFragment.class, true, arrayOfSubscriberMethodInfo41));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo42 = new SubscriberMethodInfo[3];
    arrayOfSubscriberMethodInfo42[0] = new SubscriberMethodInfo("onEventMainThread", CreateTreasuryInputResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo42[1] = new SubscriberMethodInfo("onEventMainThread", GetTreasuryBeneficiariesResponseEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo42[2] = new SubscriberMethodInfo("onEvent", ValidateTreasuryCNPResponseEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(CreateTreasuryPresenter.class, true, arrayOfSubscriberMethodInfo42));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo43 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo43[0] = new SubscriberMethodInfo("onEventMainThread", MobileTopUpVerifyEvent.class, ThreadMode.MAIN);
    putIndex(new SimpleSubscriberInfo(MobileTopUpActivity.class, true, arrayOfSubscriberMethodInfo43));
  }
  
  public EventBusIndex() {}
  
  private static void putIndex(SubscriberInfo paramSubscriberInfo)
  {
    SUBSCRIBER_INDEX.put(paramSubscriberInfo.getSubscriberClass(), paramSubscriberInfo);
  }
  
  public SubscriberInfo getSubscriberInfo(Class<?> paramClass)
  {
    SubscriberInfo localSubscriberInfo = (SubscriberInfo)SUBSCRIBER_INDEX.get(paramClass);
    if (localSubscriberInfo != null) {
      return localSubscriberInfo;
    }
    return null;
  }
}
