package com.spotify.music.libs.viewuri;

import fjq;
import uun;
import uuq;

public final class ViewUris
{
  public static final uun A;
  public static final uun B;
  public static final uun C;
  public static final uun D;
  public static final uun E;
  public static final uun F;
  public static final uun G;
  public static final uun H;
  public static final uun I;
  public static final uun J;
  public static final uun K;
  public static final uun L;
  public static final uun M;
  public static final uun N;
  public static final uun O;
  public static final uun P;
  public static final uun Q;
  public static final uun R;
  public static final uun S;
  public static final uun T;
  public static final uun U;
  public static final uun V;
  public static final uuq W;
  public static final uuq X;
  public static final uuq Y;
  public static final uuq Z;
  public static final uun a;
  public static final uuq aA;
  public static final uuq aB;
  public static final uuq aC;
  public static final uuq aD;
  public static final uuq aE;
  public static final uuq aF;
  public static final uun aG;
  public static final uun aH;
  public static final uuq aI;
  public static final uuq aJ;
  public static final uuq aK;
  public static final uuq aL;
  public static final uuq aM;
  public static final uuq aN;
  public static final uuq aO;
  public static final uuq aP;
  public static final uuq aQ;
  public static final uuq aR;
  public static final uuq aS;
  public static final uuq aT;
  public static final uuq aU;
  public static final uuq aV;
  public static final uuq aW;
  public static final uuq aX;
  public static final uuq aY;
  public static final uuq aZ;
  public static final uuq aa;
  public static final uuq ab;
  public static final uun ac;
  public static final uun ad;
  public static final uun ae;
  public static final uun af;
  public static final uun ag;
  public static final uun ah;
  public static final uun ai;
  public static final uun aj;
  public static final uun ak;
  public static final uun al;
  public static final uun am;
  public static final uun an;
  public static final uun ao;
  public static final uun ap;
  public static final uun aq;
  public static final uun ar;
  public static final uuq as;
  public static final uun at;
  public static final uun au;
  public static final uuq av;
  public static final uun aw;
  public static final uuq ax;
  public static final uuq ay;
  public static final uun az;
  public static final uun b;
  public static final uun bA;
  public static final uun bB;
  public static final uun bC;
  public static final uun bD;
  public static final uun bE;
  public static final uun bF;
  public static final uun bG;
  public static final uun bH;
  public static final uun bI;
  public static final uun bJ;
  public static final uuq bK;
  public static final uun bL;
  public static final uun bM;
  public static final uun bN;
  public static final uun bO;
  public static final uuq bP;
  public static final uuq bQ;
  public static final uun bR;
  public static final uun bS;
  public static final uun bT;
  public static final uun bU;
  public static final uun bV;
  public static final uun bW;
  public static final uun bX;
  public static final uun bY;
  public static final uun bZ;
  public static final uuq ba;
  public static final uuq bb;
  public static final uuq bc;
  public static final uuq bd;
  public static final uun be;
  public static final uun bf;
  public static final uun bg;
  public static final uun bh;
  public static final uun bi;
  public static final uun bj;
  public static final uun bk;
  public static final uun bl;
  public static final uun bm;
  public static final uun bn;
  public static final uun bo;
  public static final uun bp;
  public static final uun bq;
  public static final uun br;
  public static final uun bs;
  public static final uun bt;
  public static final uun bu;
  public static final uun bv;
  public static final uun bw;
  public static final uun bx;
  public static final uun by;
  public static final uun bz;
  public static final uun c;
  public static final uun cA;
  public static final uun cB;
  public static final uun cC;
  public static final uun cD;
  public static final uun cE;
  public static final uun cF;
  public static final uun cG = uun.a("spotify:internal:myspin");
  public static final uun cH = uun.a("spotify:internal:scannables");
  public static final uun ca;
  public static final uun cb;
  public static final uun cc;
  public static final uun cd;
  public static final uun ce;
  public static final uun cf;
  public static final uun cg;
  public static final uun ch;
  public static final uun ci;
  public static final uun cj;
  public static final uun ck;
  public static final uun cl;
  public static final uun cm;
  public static final uun cn;
  public static final uun co;
  public static final uun cp;
  public static final uun cq;
  public static final uun cr;
  public static final uuq cs;
  public static final uun ct;
  public static final uun cu;
  public static final uun cv;
  public static final uun cw;
  public static final uun cx;
  public static final uun cy;
  public static final uun cz;
  public static final uun d;
  public static final uuq e;
  public static final uun f;
  public static final uun g;
  public static final uun h;
  public static final uun i;
  public static final uun j;
  public static final uun k;
  public static final uun l;
  public static final uun m;
  public static final uuq n;
  public static final uuq o;
  public static final uuq p;
  public static final uuq q;
  public static final uuq r;
  public static final uuq s;
  public static final uuq t;
  public static final uun u;
  public static final uun v;
  public static final uun w;
  public static final uun x;
  public static final uun y;
  public static final uuq z;
  
  static
  {
    uun.a("spotify");
    a = uun.a("spotify:main");
    uun.a("spotify:navigation");
    uun.a("spotify:playlists");
    b = uun.a("spotify:app:radio");
    c = uun.a("spotify:startpage");
    d = uun.a("spotify:home");
    e = new uuq("spotify:home:[^:]+");
    f = uun.a("spotify:internal:running");
    new uuq("spotify:(internal:)?running:[^:]+:[^:]+");
    g = uun.a("spotify:app:findfriends");
    h = uun.a("spotify:findfriends:confirm");
    i = uun.a("spotify:friendsweekly:listeners-view");
    j = uun.a("spotify:friendsweekly:find-friends");
    k = uun.a("spotify:app:browse");
    l = uun.a("spotify:genre:podcasts-page");
    m = uun.a("spotify:charts:root");
    n = new uuq("spotify:charts:[^:]+");
    o = new uuq("spotify:(app:)?chart:[^:]+");
    Object localObject = new StringBuilder("spotify:genre:[^:]+");
    ((StringBuilder)localObject).append(fjq.c("(:[^:]++)?", 4));
    p = new uuq(((StringBuilder)localObject).toString());
    localObject = new StringBuilder("spotify:hub:moments");
    ((StringBuilder)localObject).append(fjq.c("(:[^:]++)?", 5));
    new uuq(((StringBuilder)localObject).toString());
    localObject = new StringBuilder("spotify:hub:music");
    ((StringBuilder)localObject).append(fjq.c("(:[^:]++)?", 5));
    new uuq(((StringBuilder)localObject).toString());
    localObject = new StringBuilder("spotify:hub:shows");
    ((StringBuilder)localObject).append(fjq.c("(:[^:]++)?", 5));
    new uuq(((StringBuilder)localObject).toString());
    localObject = new StringBuilder("spotify:(app:)?browse");
    ((StringBuilder)localObject).append(fjq.c("(:[^:]++)?", 5));
    q = new uuq(((StringBuilder)localObject).toString());
    r = new uuq("spotify:(app:)?browse");
    localObject = new StringBuilder("spotify:hub:sandbox:[^:]+");
    ((StringBuilder)localObject).append(fjq.c("(:[^:]++)?", 4));
    new uuq(((StringBuilder)localObject).toString());
    s = new uuq("spotify:special:[^:]+");
    localObject = new StringBuilder("spotify:special:[^:]+");
    ((StringBuilder)localObject).append(fjq.c("(:[^:]++)?", 4));
    t = new uuq(((StringBuilder)localObject).toString());
    u = uun.a("spotify:internal:startpage");
    v = uun.a("spotify:internal:taste:goodbye");
    w = uun.a("spotify:internal:taste:select");
    x = uun.a("spotify:internal:taste:search-artist");
    y = uun.a("spotify:internal:taste:welcome");
    z = new uuq("spotify:track:+[a-zA-Z0-9]{22}");
    A = uun.a("spotify:driving:jumpstart");
    B = uun.a("spotify:car:lockscreen");
    C = uun.a("spotify:waze:optout");
    D = uun.a("spotify:waze:onboarding");
    E = uun.a("spotify:waze:return");
    F = uun.a("spotify:assisted-curation");
    G = uun.a("spotify:assisted-curation:search");
    H = uun.a("spotify:assisted-curation:search:album");
    I = uun.a("spotify:assisted-curation:search:artist");
    J = uun.a("spotify:free-tier:create-playlist");
    K = uun.a("spotify:free-tier:add-to-playlist");
    L = uun.a("spotify:free-tier:collection");
    M = uun.a("spotify:free-tier:find");
    N = uun.a("spotify:free-tier:likes");
    O = uun.a("spotify:free-tier:likes:songs");
    P = uun.a("spotify:free-tier:profile");
    Q = uun.a("spotify:free-tier:all-songs-dialog");
    R = uun.a("spotify:free-tier:taste-onboarding:skip-dialog");
    S = uun.a("spotify:free-tier:taste-onboarding:artist-picker");
    uun.a("spotify:free-tier:taste-onboarding:artist-picker-container");
    uun.a("spotify:free-tier:taste-onboarding:liked-artists");
    T = uun.a("spotify:free-tier:taste-onboarding:artist-search");
    U = uun.a("spotify:free-tier:taste-onboarding:swipe-tracks");
    V = uun.a("spotify:free-tier:taste-onboarding:update-taste");
    W = new uuq("spotify:(user:[^:]+:)?(playlist:[a-zA-Z0-9]{22})");
    X = new uuq("spotify:(user:[^:]+:)?(playlist:[a-zA-Z0-9]{22})");
    Y = new uuq("spotify:(user:[^:]+:)?(playlist:[a-zA-Z0-9]{22})");
    Z = new uuq("spotify:(user:[^:]+:)?(playlist:[a-zA-Z0-9]{22})");
    aa = new uuq("spotify:(user:[^:]+:)?(playlist:[a-zA-Z0-9]{22})");
    ab = new uuq("spotify:(user:[^:]+:)?(playlist:[a-zA-Z0-9]{22})");
    ac = uun.a("spotify:free-tier:data-saver:learn-more");
    ad = uun.a("spotify:free-tier:data-saver:opt-in-status");
    ae = uun.a("spotify:data-saver-mode:settings");
    af = uun.a("spotify:language-picker:no-skip-dialog");
    ag = uun.a("spotify:language-picker:picker");
    ah = uun.a("spotify:internal:lyrics-full-screen");
    ai = uun.a("spotify:internal:nft:education:favorites-mix");
    aj = uun.a("spotify:config");
    ak = uun.a("spotify:now-playing");
    al = uun.a("spotify:now-playing-bar");
    am = uun.a("spotify:now-playing-view");
    an = uun.a("spotify:now-playing-view-v2");
    ao = uun.a("spotify:queue");
    ap = uun.a("spotify:widget");
    aq = uun.a("spotify:app:concerts");
    ar = uun.a("spotify:app:concerts:concert-group");
    as = new uuq("spotify:concerts?:(songkick:events:)?[^:]+");
    at = uun.a("spotify:concerts:location-search");
    au = uun.a("spotify:find");
    new uuq("spotify:find:[^:]+");
    localObject = new uuq("spotify:search(:.*)?");
    av = (uuq)localObject;
    aw = ((uuq)localObject).a("spotify:search");
    ax = new uuq("spotify:search(:[^:]+)(:.+)");
    localObject = new uuq("spotify:radio:create_station(:.*)?");
    ay = (uuq)localObject;
    az = ((uuq)localObject).a("spotify:radio:create_station");
    aA = new uuq("spotify:radio:create_station(:[^:]+)(:.+)");
    aB = new uuq("spotify:station:(artist:[a-zA-Z0-9]{22}|album:[a-zA-Z0-9]{22}|track:+[a-zA-Z0-9]{22}|genre:[^:]+|(user:[^:]+:)?(playlist:[a-zA-Z0-9]{22})|playlist:[a-zA-Z0-9]{22}|user:[^:]+:cluster:[a-zA-Z0-9]{22}|user:[^:]+:clusters|dailymix:[a-zA-Z0-9]{22})|spotify:dailymix:[a-zA-Z0-9]{22}");
    aC = new uuq("spotify:(artist:[a-zA-Z0-9]{22}|album:[a-zA-Z0-9]{22}|track:+[a-zA-Z0-9]{22}|genre:[^:]+|(user:[^:]+:)?(playlist:[a-zA-Z0-9]{22})|playlist:[a-zA-Z0-9]{22}|user:[^:]+:cluster:[a-zA-Z0-9]{22})");
    aD = new uuq("spotify:station:user:[^:]+:cluster:[a-zA-Z0-9]{22}");
    aE = new uuq("spotify:station:user:[^:]+:clusters");
    aF = new uuq("spotify:dailymix:[a-zA-Z0-9]{22}");
    aG = uun.a("spotify:daily-mix-hub");
    aH = uun.a("spotify:made-for-you");
    aI = new uuq("spotify:station:artist:[a-zA-Z0-9]{22}");
    aJ = new uuq("spotify:station:album:[a-zA-Z0-9]{22}");
    aK = new uuq("spotify:station:track:+[a-zA-Z0-9]{22}");
    aL = new uuq("spotify:station:genre:[^:]+");
    aM = new uuq("spotify:station:((user:[^:]+:)?(playlist:[a-zA-Z0-9]{22}))");
    aN = new uuq("spotify:radio:artist:[a-zA-Z0-9]{22}");
    aO = new uuq("spotify:radio:album:[a-zA-Z0-9]{22}");
    aP = new uuq("spotify:radio:track:+[a-zA-Z0-9]{22}");
    aQ = new uuq("spotify:radio:genre:[^:]+");
    aR = new uuq("spotify:radio:((user:[^:]+:)?(playlist:[a-zA-Z0-9]{22}))");
    aS = new uuq("spotify:user:[^:]+");
    aT = new uuq("spotify:(user:[^:]+:)?(playlist:[a-zA-Z0-9]{22})");
    localObject = new StringBuilder("spotify:internal:format_list_chart:(");
    ((StringBuilder)localObject).append(aT);
    ((StringBuilder)localObject).append(')');
    aU = new uuq(((StringBuilder)localObject).toString());
    localObject = new StringBuilder("spotify:internal:format_list_data_saver:(");
    ((StringBuilder)localObject).append(aT);
    ((StringBuilder)localObject).append(')');
    aV = new uuq(((StringBuilder)localObject).toString());
    localObject = new StringBuilder("spotify:internal:format_list_personalized_sets:(");
    ((StringBuilder)localObject).append(aT);
    ((StringBuilder)localObject).append(')');
    aW = new uuq(((StringBuilder)localObject).toString());
    localObject = new StringBuilder("spotify:internal:format_list_show:(");
    ((StringBuilder)localObject).append(aT);
    ((StringBuilder)localObject).append(')');
    aX = new uuq(((StringBuilder)localObject).toString());
    localObject = new StringBuilder("spotify:internal:format_list_show_shuffle:(");
    ((StringBuilder)localObject).append(aT);
    ((StringBuilder)localObject).append(')');
    aY = new uuq(((StringBuilder)localObject).toString());
    localObject = new StringBuilder("spotify:internal:podcast_episode_list:(");
    ((StringBuilder)localObject).append(aT);
    ((StringBuilder)localObject).append(')');
    aZ = new uuq(((StringBuilder)localObject).toString());
    localObject = new StringBuilder("spotify:internal:format_list_friends_weekly:(");
    ((StringBuilder)localObject).append(aT);
    ((StringBuilder)localObject).append(')');
    ba = new uuq(((StringBuilder)localObject).toString());
    bb = new uuq("spotify:user:[^:]+:folder:[a-zA-Z0-9]+");
    bc = new uuq("spotify:album:[a-zA-Z0-9]{22}");
    bd = new uuq("spotify:artist:[a-zA-Z0-9]{22}(:about|:albums|:singles|:appears_on|:appears-on|:compilations|:related|:releases|:biography|:gallery|:playlists|:radio|:concert|:concerts)?");
    be = uun.a("spotify:intro:tos:dialog");
    bf = uun.a("spotify:intro:tos:text");
    uun.a("spotify:invite:start");
    uun.a("spotify:invite:have-invite");
    uun.a("spotify:invite:confirmation");
    uun.a("spotify:settings:lastfm_login_dialog");
    uun.a("spotify:login:facebook");
    uun.a("spotify:login:welcome");
    bg = uun.a("spotify:login:resetpassword");
    bh = uun.a("spotify:internal:preferences:facebook-connect");
    uun.a("spotify:signup-v1:login");
    uun.a("spotify:add_to_playlist");
    uun.a("spotify:create_rename_playlist");
    bi = uun.a("spotify:offline_sync_error");
    bj = uun.a("spotify:disk_almost_full");
    bk = uun.a("spotify:debug");
    bl = uun.a("spotify:app:upsell");
    bm = uun.a("spotify:upsell:choose_extreme_quality");
    bn = uun.a("spotify:upsell:stuck_in_shuffle");
    bo = uun.a("spotify:upsell:out_of_skips");
    bp = uun.a("spotify:upsell:no_offline");
    bq = uun.a("spotify:upsell:no_offline");
    br = uun.a("spotify:upsell:no_queue");
    bs = uun.a("spotify:upsell:trial-started");
    bt = uun.a("spotify:upsell:trial-ended");
    bu = uun.a("spotify:upsell:capping_reached");
    bv = uun.a("spotify:upsell:showcase");
    bw = uun.a("spotify:upsell:content-unavailable");
    bx = uun.a("spotify:upsell:premium_in_app_destination");
    by = uun.a("spotify:premium:activation");
    uun.a("spotify:upsell:auto_7day_trial");
    bz = uun.a("spotify:ads:mobile_video_takeover");
    bA = uun.a("spotify:ads:facebook_audience_network");
    bB = uun.a("spotify:ads:sponsored_session");
    bC = uun.a("spotify:ads:screen_saver");
    bD = uun.a("spotify:dynamic_upsell");
    bE = uun.a("spotify:internal:premium_signup");
    uun.a("spotify:share");
    uun.a("spotify:app:share");
    bF = uun.a("spotify:app:share-flow");
    bG = uun.a("spotify:app:share:facebook-stories");
    bH = uun.a("spotify:app:share:instagram-stories");
    uun.a("spotify:app:share-flow-chooser-messenger");
    uun.a("spotify:share:connect:facebook");
    bI = uun.a("spotify:share:missing-user");
    uun.a("spotify:licenses");
    uun.a("spotify:update");
    uun.a("spotify:delete_cache_dialog");
    uun.a("spotify:delete_cache_dialog_confirm");
    bJ = uun.a("spotify:collection");
    uun.a("spotify:collection:nft-mixes");
    bK = new uuq("spotify:user:[^:]+:collection");
    bL = uun.a("spotify:internal:collection:playlists");
    bM = uun.a("spotify:internal:collection:radio");
    bN = uun.a("spotify:internal:collection:artists");
    bO = uun.a("spotify:internal:collection:albums");
    bP = new uuq("spotify:user:[^:]+:collection:album:[a-zA-Z0-9]{22}");
    bQ = new uuq("spotify:user:[^:]+:collection:artist:[a-zA-Z0-9]{22}");
    bR = uun.a("spotify:internal:collection:tracks");
    uun.a("spotify:internal:collection:shows");
    bS = uun.a("spotify:collection:podcasts:following");
    bT = uun.a("spotify:internal:collection:offlined-episodes");
    bU = uun.a("spotify:internal:collection:unplayed-episodes");
    uun.a("spotify:internal:gaia");
    bV = uun.a("spotify:internal:connect-device-picker");
    bW = uun.a("spotify:internal:connect-device-context-menu");
    bX = uun.a("spotify:internal:gaia-onboarding-popup");
    uun.a("spotify:internal:gaia-onboarding-popup-educational");
    bY = uun.a("spotify:internal:gaia-popup");
    bZ = uun.a("spotify:internal:gaia-volume");
    ca = uun.a("spotify:internal:connect-tutorial-desktop");
    cb = uun.a("spotify:internal:connect-tutorial-speaker");
    cc = uun.a("spotify:internal:connect-tutorial-tv");
    cd = uun.a("spotify:internal:preferences:push_notification");
    ce = uun.a("spotify:internal:local_files_import");
    cf = uun.a("spotify:internal:local_files_import:folders");
    cg = uun.a("spotify:internal:local_files_import:artists");
    ch = uun.a("spotify:internal:local_files_import:albums");
    ci = uun.a("spotify:internal:local_files_import:songs");
    cj = uun.a("spotify:internal:notification");
    ck = uun.a("spotify:internal:preferences:storage");
    cl = uun.a("spotify:config:account");
    cm = uun.a("spotify:internal:tutorials");
    cn = uun.a("spotify:arsenal");
    co = uun.a("spotify:cover-image");
    cp = uun.a("spotify:request-permissions");
    uun.a("spotify:media_controller");
    cq = uun.a("spotify:app:app_rater");
    uun.a("spotify:signup:communications:dialog");
    cr = uun.a("spotify:media_service");
    cs = new uuq("spotify:show:[a-zA-Z0-9]{22}");
    uun.a("spotify:ad_subscriptions");
    uun.a("spotify:churn_locked_state");
    ct = uun.a("spotify:remove_all_episodes");
    cu = uun.a("spotify:fullscreen_videoplayer");
    cv = uun.a("spotify:voice-assistant");
    cw = uun.a("spotify:voice-assistant:confirmation");
    cx = uun.a("spotify:voice-assistant:now-playing");
    cy = uun.a("spotify:voice-assistant:onboarding");
    cz = uun.a("spotify:voice-assistant:error");
    cA = uun.a("spotify:internal:service");
    cB = uun.a("spotify:onboarding:overlay:shuffle-playlist");
    cC = uun.a("spotify:onboarding:overlay:migration:welcome");
    cD = uun.a("spotify:onboarding:overlay:migration:on-demand");
    cE = uun.a("spotify:onboarding:overlay:migration:recs");
    cF = uun.a("spotify:onboarding:overlay:migration:playlist");
    uun.a("spotify:onboarding:education:migration:favorite-playlist");
    uun.a("spotify:onboarding:education:migration:users-playlist");
  }
}
