package o;

import com.google.android.gms.common.api.Status;

public final class dM<R extends cr>
  extends co<R>
{
  private final Status ˎ;
  
  public final Integer ˊ()
  {
    throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
  }
  
  public final void ˋ()
  {
    throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
  }
  
  final Status ˎ()
  {
    return this.ˎ;
  }
  
  public final void ˎ(co.ˋ paramˋ)
  {
    throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
  }
  
  public final void ॱ(ct<? super R> paramCt)
  {
    throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
  }
  
  public final boolean ॱ()
  {
    throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
  }
}
