package com.kbank.otp.finance;

import android.text.TextUtils;
import java.io.Serializable;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

public class Category
  implements Serializable
{
  public static final Map<String, Integer> sIcons = new HashMap();
  private static final long serialVersionUID = 7851735304429908807L;
  public String icon;
  public String id;
  public String name;
  public List<Category> subcategories;
  public String type;
  
  static
  {
    Map localMap = sIcons;
    int j = 0 + 1;
    localMap.put(Integer.toString(0), Integer.valueOf(2130837705));
    localMap = sIcons;
    int i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130838034));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837770));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130838048));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837728));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837909));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130838044));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837955));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837585));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837716));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837717));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837720));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837692));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130838027));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130838012));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130838029));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837723));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837784));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837721));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837719));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837775));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837648));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837859));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130838049));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837861));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837729));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837732));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837710));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837583));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837711));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837726));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837943));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837709));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837718));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130838011));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837722));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837911));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837959));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130838028));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837882));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837725));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837724));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837976));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837889));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837584));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130838043));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837587));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837588));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837589));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837596));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837597));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837598));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837599));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837600));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837601));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837602));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837604));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837603));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837606));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837607));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837608));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837642));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837643));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837644));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837645));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837646));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837647));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837649));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837650));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837651));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837652));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837653));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837654));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837655));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837662));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837656));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837657));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837659));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837658));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837660));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837661));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837663));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837664));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837665));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837666));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837667));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837668));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837669));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837670));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837693));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837714));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837715));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837727));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837730));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837731));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837771));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837772));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837773));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837774));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837776));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837777));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837778));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837779));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837780));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837781));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837782));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837783));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837785));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837786));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837860));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837862));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837863));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837864));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837867));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837868));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837869));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837870));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837871));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837872));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837873));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837875));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837876));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837877));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837881));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837886));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837887));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837888));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837892));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837893));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837891));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837894));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837895));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837910));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837912));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837913));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837914));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837938));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837939));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837940));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837941));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837942));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837944));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837945));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837946));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837947));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837948));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837949));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837950));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837951));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837956));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837957));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837958));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837960));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837961));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837962));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837963));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837964));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837965));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837971));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837972));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837969));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837970));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837973));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837974));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837975));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837978));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837979));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837981));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130837980));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130837982));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130838019));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130838024));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130838025));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130838026));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130838030));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130838031));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130838032));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130838033));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130838046));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130838045));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130838047));
    localMap = sIcons;
    i = j + 1;
    localMap.put(Integer.toString(j), Integer.valueOf(2130838050));
    localMap = sIcons;
    j = i + 1;
    localMap.put(Integer.toString(i), Integer.valueOf(2130838051));
    sIcons.put(Integer.toString(j), Integer.valueOf(2130838052));
  }
  
  public Category() {}
  
  public static String getIdByResId(int paramInt)
  {
    Iterator localIterator = sIcons.entrySet().iterator();
    while (localIterator.hasNext())
    {
      Map.Entry localEntry = (Map.Entry)localIterator.next();
      if (((Integer)localEntry.getValue()).intValue() == paramInt) {
        return (String)localEntry.getKey();
      }
    }
    return "0";
  }
  
  public static int getResId(String paramString)
  {
    Map localMap = sIcons;
    if ((!TextUtils.isEmpty(paramString)) && (sIcons.containsKey(paramString))) {}
    for (;;)
    {
      return ((Integer)localMap.get(paramString)).intValue();
      paramString = "0";
    }
  }
  
  public int getResId()
  {
    Map localMap = sIcons;
    if ((!TextUtils.isEmpty(this.icon)) && (sIcons.containsKey(this.icon))) {}
    for (String str = this.icon;; str = "0") {
      return ((Integer)localMap.get(str)).intValue();
    }
  }
}
