import android.content.Context;
import android.content.SharedPreferences;
import android.content.SharedPreferences.Editor;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.json.JSONObject;

@fug
public final class fhv
{
  public static final fhk<String> A;
  public static final fhk<Integer> B;
  public static final fhk<Boolean> C;
  public static final fhk<Boolean> D;
  public static final fhk<String> E;
  public static final fhk<String> F;
  public static final fhk<String> G;
  public static final fhk<Boolean> H;
  public static final fhk<String> I;
  public static final fhk<Boolean> J;
  public static final fhk<Boolean> K;
  public static final fhk<Integer> L;
  public static final fhk<Integer> M;
  public static final fhk<Integer> N;
  public static final fhk<Integer> O;
  public static final fhk<Integer> P;
  public static final fhk<Boolean> Q;
  public static final fhk<Integer> R;
  public static final fhk<Boolean> S;
  public static final fhk<Integer> T;
  public static final fhk<Integer> U;
  public static final fhk<String> V;
  public static final fhk<String> W;
  public static final fhk<Boolean> X;
  public static final fhk<Boolean> Y;
  public static final fhk<Boolean> Z;
  public static final fhk<String> a;
  public static final fhk<Boolean> aA;
  public static final fhk<Boolean> aB;
  public static final fhk<Long> aC;
  public static final fhk<Boolean> aD;
  public static final fhk<Boolean> aE;
  public static final fhk<Boolean> aF;
  public static final fhk<Boolean> aG;
  public static final fhk<String> aH;
  public static final fhk<String> aI;
  public static final fhk<Integer> aJ;
  public static final fhk<Integer> aK;
  public static final fhk<Integer> aL;
  public static final fhk<String> aM;
  public static final fhk<Integer> aN;
  public static final fhk<Integer> aO;
  public static final fhk<Long> aP;
  public static final fhk<Long> aQ;
  public static final fhk<Float> aR;
  public static final fhk<Float> aS;
  public static final fhk<Boolean> aT;
  public static final fhk<Boolean> aU;
  public static final fhk<String> aV;
  public static final fhk<String> aW;
  public static final fhk<Boolean> aX;
  public static final fhk<Boolean> aY;
  public static final fhk<Long> aZ;
  public static final fhk<Long> aa;
  public static final fhk<Boolean> ab;
  public static final fhk<Boolean> ac;
  public static final fhk<Boolean> ad;
  public static final fhk<Boolean> ae;
  public static final fhk<Boolean> af;
  public static final fhk<Boolean> ag;
  public static final fhk<Boolean> ah;
  public static final fhk<Boolean> ai;
  public static final fhk<Boolean> aj;
  public static final fhk<String> ak;
  public static final fhk<String> al;
  public static final fhk<Boolean> am;
  public static final fhk<Boolean> an;
  public static final fhk<String> ao;
  public static final fhk<Long> ap;
  public static final fhk<Integer> aq;
  public static final fhk<Boolean> ar;
  public static final fhk<Boolean> as;
  public static final fhk<Long> at;
  public static final fhk<Boolean> au;
  public static final fhk<Long> av;
  public static final fhk<Long> aw;
  public static final fhk<Boolean> ax;
  public static final fhk<Long> ay;
  public static final fhk<Boolean> az;
  public static final fhk<Boolean> b;
  public static final fhk<Boolean> bA;
  public static final fhk<Boolean> bB;
  public static final fhk<Boolean> bC;
  public static final fhk<Boolean> bD;
  public static final fhk<Boolean> bE;
  public static final fhk<Boolean> bF;
  public static final fhk<String> bG;
  public static final fhk<Long> bH;
  public static final fhk<Boolean> bI;
  public static final fhk<Boolean> bJ;
  public static final fhk<String> bK;
  public static final fhk<String> bL;
  public static final fhk<Boolean> bM;
  public static final fhk<Boolean> bN;
  public static final fhk<Boolean> bO;
  public static final fhk<Integer> bP;
  public static final fhk<String> bQ;
  public static final fhk<Boolean> bR;
  public static final fhk<Boolean> bS;
  public static final fhk<Boolean> bT;
  public static final fhk<Boolean> bU;
  public static final fhk<Boolean> bV;
  public static final fhk<Boolean> bW;
  public static final fhk<Boolean> bX;
  public static final fhk<Long> bY;
  public static final fhk<Integer> bZ;
  public static final fhk<Boolean> ba;
  public static final fhk<Boolean> bb;
  public static final fhk<Long> bc;
  public static final fhk<Boolean> bd;
  public static final fhk<Boolean> be;
  public static final fhk<Boolean> bf;
  public static final fhk<Boolean> bg;
  public static final fhk<Long> bh;
  public static final fhk<Boolean> bi;
  public static final fhk<Boolean> bj;
  public static final fhk<Boolean> bk;
  public static final fhk<Long> bl;
  public static final fhk<Long> bm;
  public static final fhk<Long> bn;
  public static final fhk<Boolean> bo;
  public static final fhk<Long> bp;
  public static final fhk<Boolean> bq;
  public static final fhk<Boolean> br;
  public static final fhk<Boolean> bs;
  public static final fhk<Boolean> bt;
  public static final fhk<Integer> bu;
  public static final fhk<Boolean> bv;
  public static final fhk<Boolean> bw;
  public static final fhk<String> bx;
  public static final fhk<Boolean> by;
  public static final fhk<Boolean> bz;
  public static final fhk<Boolean> c;
  public static final fhk<String> cA;
  public static final fhk<String> cB;
  public static final fhk<String> cC;
  public static final fhk<String> cD;
  public static final fhk<Integer> cE;
  public static final fhk<Integer> cF;
  public static final fhk<Boolean> cG;
  public static final fhk<Boolean> cH;
  public static final fhk<Integer> cI;
  public static final fhk<Boolean> cJ;
  public static final fhk<Boolean> cK;
  public static final fhk<Integer> cL;
  public static final fhk<Long> cM = fhk.a(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000L);
  public static final fhk<String> cN = fhk.a(0, "gads:public_beta:traffic_multiplier", "1.0");
  public static final fhk<Boolean> cO = fhk.a(1, "gads:real_test_request:enabled", Boolean.valueOf(true));
  public static final fhk<Boolean> cP = fhk.a(1, "gads:real_test_request:render_webview_label", Boolean.valueOf(true));
  public static final fhk<Boolean> cQ = fhk.a(1, "gads:real_test_request:render_native_label", Boolean.valueOf(true));
  private static fhk<String> cR = fhk.a(0, "gads:sdk_core_experiment_id");
  private static fhk<String> cS;
  private static fhk<Boolean> cT;
  private static fhk<String> cU;
  private static fhk<Boolean> cV;
  private static fhk<String> cW;
  private static fhk<String> cX;
  private static fhk<String> cY;
  private static fhk<Integer> cZ;
  public static final fhk<Integer> ca;
  public static final fhk<Long> cb;
  public static final fhk<Boolean> cc;
  public static final fhk<Long> cd;
  public static final fhk<String> ce;
  public static final fhk<String> cf;
  public static final fhk<String> cg;
  public static final fhk<String> ch;
  public static final fhk<String> ci;
  public static final fhk<Long> cj;
  public static final fhk<Long> ck;
  public static final fhk<Boolean> cl;
  public static final fhk<Boolean> cm;
  public static final fhk<Boolean> cn;
  public static final fhk<Boolean> co;
  public static final fhk<Boolean> cp;
  public static final fhk<Long> cq;
  public static final fhk<Boolean> cr;
  public static final fhk<Boolean> cs;
  public static final fhk<String> ct;
  public static final fhk<Integer> cu;
  public static final fhk<Boolean> cv;
  public static final fhk<Boolean> cw;
  public static final fhk<Boolean> cx;
  public static final fhk<Boolean> cy;
  public static final fhk<Boolean> cz;
  public static final fhk<String> d;
  private static fhk<String> dA;
  private static fhk<Long> dB;
  private static fhk<Boolean> dC;
  private static fhk<Boolean> dD;
  private static fhk<String> dE;
  private static fhk<String> dF;
  private static fhk<Boolean> dG;
  private static fhk<String> dH;
  private static fhk<String> dI;
  private static fhk<String> dJ;
  private static fhk<Boolean> dK;
  private static fhk<String> dL;
  private static fhk<String> dM;
  private static fhk<Long> dN;
  private static fhk<String> dO;
  private static fhk<String> dP;
  private static fhk<String> dQ;
  private static fhk<Boolean> dR;
  private static fhk<Boolean> dS;
  private static fhk<Boolean> dT;
  private static fhk<String> dU;
  private static fhk<Long> dV;
  private static fhk<Integer> dW;
  private static fhk<Integer> dX;
  private static fhk<Long> dY;
  private static fhk<Boolean> dZ;
  private static fhk<String> da;
  private static fhk<Boolean> db;
  private static fhk<Float> dc;
  private static fhk<String> dd;
  private static fhk<String> de;
  private static fhk<Boolean> df;
  private static fhk<Float> dg;
  private static fhk<Boolean> dh;
  private static fhk<String> di;
  private static fhk<Boolean> dj;
  private static fhk<String> dk;
  private static fhk<String> dl;
  private static fhk<String> dm;
  private static fhk<Boolean> dn;
  private static fhk<Integer> jdField_do;
  private static fhk<String> dp;
  private static fhk<Boolean> dq;
  private static fhk<Boolean> dr;
  private static fhk<String> ds;
  private static fhk<Integer> dt;
  private static fhk<Integer> du;
  private static fhk<Integer> dv;
  private static fhk<Boolean> dw;
  private static fhk<Boolean> dx;
  private static fhk<Boolean> dy;
  private static fhk<Boolean> dz;
  public static final fhk<Boolean> e;
  private static fhk<Long> ea;
  private static fhk<Long> eb;
  private static fhk<Boolean> ec;
  private static fhk<Boolean> ed;
  private static fhk<String> ee;
  private static fhk<Boolean> ef;
  private static fhk<String> eg;
  private static fhk<Boolean> eh;
  private static fhk<Boolean> ei;
  private static fhk<String> ej;
  private static fhk<Boolean> ek;
  private static fhk<String> el;
  private static fhk<Boolean> em;
  private static byte[] en;
  public static final fhk<String> f;
  public static final fhk<Integer> g;
  public static final fhk<Integer> h;
  public static final fhk<Integer> i;
  public static final fhk<Integer> j;
  public static final fhk<Integer> k;
  public static final fhk<Integer> l;
  public static final fhk<Long> m;
  public static final fhk<Long> n;
  public static final fhk<Integer> o;
  public static final fhk<Boolean> p;
  public static final fhk<String> q;
  public static final fhk<Long> r;
  public static final fhk<Boolean> s;
  public static final fhk<Long> t;
  public static final fhk<Boolean> u;
  public static final fhk<Integer> v;
  public static final fhk<Long> w;
  public static final fhk<Boolean> x;
  public static final fhk<Boolean> y;
  public static final fhk<Boolean> z;
  
  static
  {
    a = fhk.a(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
    cS = fhk.a(0, "gads:sdk_core_js_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.js");
    cT = fhk.a(0, "gads:request_builder:singleton_webview", Boolean.valueOf(false));
    cU = fhk.a(0, "gads:request_builder:singleton_webview_experiment_id");
    cV = fhk.a(0, "gads:sdk_use_dynamic_module", Boolean.valueOf(true));
    cW = fhk.a(0, "gads:sdk_use_dynamic_module_experiment_id");
    b = fhk.a(0, "gads:sdk_crash_report_enabled", Boolean.valueOf(false));
    c = fhk.a(0, "gads:sdk_crash_report_full_stacktrace", Boolean.valueOf(false));
    d = fhk.a(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    e = fhk.a(0, "gads:block_autoclicks", Boolean.valueOf(false));
    cX = fhk.a(0, "gads:block_autoclicks_experiment_id");
    cY = fhk.a(0, "gads:spam_app_context:experiment_id");
    cZ = fhk.a(1, "gads:http_url_connection_factory:timeout_millis", 10000);
    f = fhk.a(1, "gads:video_exo_player:version", "1");
    g = fhk.a(1, "gads:video_exo_player:connect_timeout", 8000);
    h = fhk.a(1, "gads:video_exo_player:read_timeout", 8000);
    i = fhk.a(1, "gads:video_exo_player:loading_check_interval", 1048576);
    da = fhk.a(0, "gads:video_stream_cache:experiment_id");
    j = fhk.a(1, "gads:video_stream_cache:limit_count", 5);
    k = fhk.a(1, "gads:video_stream_cache:limit_space", 8388608);
    l = fhk.a(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    m = fhk.a(1, "gads:video_stream_cache:limit_time_sec", 300L);
    n = fhk.a(1, "gads:video_stream_cache:notify_interval_millis", 125L);
    o = fhk.a(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    p = fhk.a(0, "gads:video:metric_reporting_enabled", Boolean.valueOf(false));
    q = fhk.a(1, "gads:video:metric_frame_hash_times", "");
    r = fhk.a(1, "gads:video:metric_frame_hash_time_leniency", 500L);
    s = fhk.a(1, "gads:video:force_watermark", Boolean.valueOf(false));
    t = fhk.a(1, "gads:video:surface_update_min_spacing_ms", 1000L);
    u = fhk.a(1, "gads:video:spinner:enabled", Boolean.valueOf(false));
    v = fhk.a(1, "gads:video:spinner:scale", 4);
    w = fhk.a(1, "gads:video:spinner:jank_threshold_ms", 50L);
    x = fhk.a(1, "gads:video:aggressive_media_codec_release", Boolean.valueOf(false));
    y = fhk.a(1, "gads:memory_bundle:debug_info", Boolean.valueOf(false));
    z = fhk.a(1, "gads:memory_bundle:runtime_info", Boolean.valueOf(true));
    A = fhk.a(1, "gads:video:codec_query_mime_types", "");
    B = fhk.a(1, "gads:video:codec_query_minimum_version", 16);
    db = fhk.a(0, "gads:ad_id_app_context:enabled", Boolean.valueOf(false));
    dc = fhk.a(0, "gads:ad_id_app_context:ping_ratio", 0.0F);
    dd = fhk.a(0, "gads:ad_id_app_context:experiment_id");
    de = fhk.a(0, "gads:ad_id_use_shared_preference:experiment_id");
    df = fhk.a(0, "gads:ad_id_use_shared_preference:enabled", Boolean.valueOf(false));
    dg = fhk.a(0, "gads:ad_id_use_shared_preference:ping_ratio", 0.0F);
    dh = fhk.a(0, "gads:ad_id_use_persistent_service:enabled", Boolean.valueOf(false));
    di = fhk.b(0, "gads:looper_for_gms_client:experiment_id");
    C = fhk.a(0, "gads:looper_for_gms_client:enabled", Boolean.valueOf(true));
    D = fhk.a(0, "gads:sw_ad_request_service:enabled", Boolean.valueOf(true));
    dj = fhk.a(0, "gads:sw_dynamite:enabled", Boolean.valueOf(true));
    E = fhk.a(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
    F = fhk.a(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
    G = fhk.a(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
    H = fhk.a(0, "gads:enabled_sdk_csi", Boolean.valueOf(false));
    I = fhk.a(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
    J = fhk.a(0, "gads:sdk_csi_write_to_file", Boolean.valueOf(false));
    K = fhk.a(0, "gads:enable_content_fetching", Boolean.valueOf(true));
    L = fhk.a(0, "gads:content_length_weight", 1);
    M = fhk.a(0, "gads:content_age_weight", 1);
    N = fhk.a(0, "gads:min_content_len", 11);
    O = fhk.a(0, "gads:fingerprint_number", 10);
    P = fhk.a(0, "gads:sleep_sec", 10);
    Q = fhk.a(1, "gads:enable_content_url_hash", Boolean.valueOf(true));
    R = fhk.a(1, "gads:content_vertical_fingerprint_number", 100);
    S = fhk.a(1, "gads:enable_content_vertical_hash", Boolean.valueOf(true));
    T = fhk.a(1, "gads:content_vertical_fingerprint_bits", 23);
    U = fhk.a(1, "gads:content_vertical_fingerprint_ngram", 3);
    V = fhk.a(1, "gads:content_fetch_view_tag_id", "googlebot");
    W = fhk.a(1, "gads:content_fetch_exclude_view_tag", "none");
    X = fhk.a(0, "gad:app_index_enabled", Boolean.valueOf(true));
    Y = fhk.a(1, "gads:content_fetch_disable_get_title_from_webview", Boolean.valueOf(false));
    Z = fhk.a(0, "gads:app_index:without_content_info_present:enabled", Boolean.valueOf(true));
    aa = fhk.a(0, "gads:app_index:timeout_ms", 1000L);
    dk = fhk.a(0, "gads:app_index:experiment_id");
    dl = fhk.a(0, "gads:kitkat_interstitial_workaround:experiment_id");
    ab = fhk.a(0, "gads:kitkat_interstitial_workaround:enabled", Boolean.valueOf(true));
    ac = fhk.a(0, "gads:interstitial_follow_url", Boolean.valueOf(true));
    ad = fhk.a(0, "gads:interstitial_follow_url:register_click", Boolean.valueOf(true));
    dm = fhk.a(0, "gads:interstitial_follow_url:experiment_id");
    dn = fhk.a(0, "gads:analytics_enabled", Boolean.valueOf(true));
    ae = fhk.a(0, "gads:ad_key_enabled", Boolean.valueOf(false));
    af = fhk.a(1, "gads:sai:enabled", Boolean.valueOf(true));
    ag = fhk.a(1, "gads:sai:banner_ad_enabled", Boolean.valueOf(true));
    ah = fhk.a(1, "gads:sai:native_ad_enabled", Boolean.valueOf(true));
    ai = fhk.a(1, "gads:sai:interstitial_ad_enabled", Boolean.valueOf(true));
    aj = fhk.a(1, "gads:sai:rewardedvideo_ad_enabled", Boolean.valueOf(true));
    ak = fhk.a(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
    al = fhk.a(1, "gads:sai:impression_ping_schema_v2", "^[^?]*/adview.*");
    am = fhk.a(1, "gads:sai:click_gmsg_enabled", Boolean.valueOf(true));
    an = fhk.a(1, "gads:sai:using_macro:enabled", Boolean.valueOf(false));
    ao = fhk.a(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
    ap = fhk.a(1, "gads:sai:timeout_ms", -1L);
    aq = fhk.a(1, "gads:sai:scion_thread_pool_size", 5);
    do = fhk.a(0, "gads:webview_cache_version", 0);
    ar = fhk.a(1, "gads:webview:ignore_over_scroll", Boolean.valueOf(true));
    dp = fhk.b(0, "gads:pan:experiment_id");
    as = fhk.a(1, "gads:rewarded:adapter_initialization_enabled", Boolean.valueOf(false));
    at = fhk.a(1, "gads:rewarded:adapter_timeout_ms", 20000L);
    au = fhk.a(1, "gads:app_activity_tracker:enabled", Boolean.valueOf(true));
    av = fhk.a(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500L);
    aw = fhk.a(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5L));
    ax = fhk.a(1, "gads:adid_values_in_adrequest:enabled", Boolean.valueOf(false));
    ay = fhk.a(1, "gads:adid_values_in_adrequest:timeout", 2000L);
    az = fhk.a(1, "gads:disable_adid_values_in_ms", Boolean.valueOf(false));
    aA = fhk.a(1, "gads:enable_ad_loader_manager", Boolean.valueOf(true));
    dq = fhk.a(0, "gads:ad_serving:enabled", Boolean.valueOf(true));
    aB = fhk.a(1, "gads:ad_manager_enforce_arp_invariant:enabled", Boolean.valueOf(false));
    aC = fhk.a(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000L);
    aD = fhk.a(1, "gads:interstitial_ad_immersive_mode", Boolean.valueOf(true));
    aE = fhk.a(1, "gads:custom_close_blocking:enabled", Boolean.valueOf(false));
    dr = fhk.a(1, "gads:impression_optimization_enabled", Boolean.valueOf(false));
    ds = fhk.a(1, "gads:banner_ad_pool:schema", "customTargeting");
    dt = fhk.a(1, "gads:banner_ad_pool:max_queues", 3);
    du = fhk.a(1, "gads:banner_ad_pool:max_pools", 3);
    aF = fhk.a(1, "gads:interstitial_ad_pool:enabled", Boolean.valueOf(false));
    aG = fhk.a(1, "gads:interstitial_ad_pool:enabled_for_rewarded", Boolean.valueOf(false));
    aH = fhk.a(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    aI = fhk.a(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    aJ = fhk.a(1, "gads:interstitial_ad_pool:max_pools", 3);
    aK = fhk.a(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    aL = fhk.a(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    aM = fhk.a(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    aN = fhk.a(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
    aO = fhk.a(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
    aP = fhk.a(1, "gads:interstitial_ad_pool:discard_thresholds", 0L);
    aQ = fhk.a(1, "gads:interstitial_ad_pool:miss_thresholds", 0L);
    aR = fhk.a(1, "gads:interstitial_ad_pool:discard_asymptote", 0.0F);
    aS = fhk.a(1, "gads:interstitial_ad_pool:miss_asymptote", 0.0F);
    aT = fhk.a(0, "gads:debug_logging_feature:enable", Boolean.valueOf(false));
    aU = fhk.a(0, "gads:debug_logging_feature:intercept_web_view", Boolean.valueOf(false));
    dv = fhk.a(1, "gads:heap_wastage:bytes", 0);
    aV = fhk.a(1, "gads:spherical_video:vertex_shader", "");
    aW = fhk.a(1, "gads:spherical_video:fragment_shader", "");
    aX = fhk.a(0, "gads:log:verbose_enabled", Boolean.valueOf(false));
    aY = fhk.a(1, "gads:include_local_global_rectangles", Boolean.valueOf(false));
    aZ = fhk.a(1, "gads:position_watcher:throttle_ms", 200L);
    ba = fhk.a(1, "gads:include_lock_screen_apps_for_visibility", Boolean.valueOf(true));
    bb = fhk.a(0, "gads:device_info_caching:enabled", Boolean.valueOf(true));
    bc = fhk.a(0, "gads:device_info_caching_expiry_ms:expiry", 300000L);
    bd = fhk.a(0, "gads:gen204_signals:enabled", Boolean.valueOf(false));
    be = fhk.a(0, "gads:webview:error_reporting_enabled", Boolean.valueOf(false));
    dw = fhk.a(0, "gads:adid_reporting:enabled", Boolean.valueOf(false));
    dx = fhk.a(0, "gads:ad_settings_page_reporting:enabled", Boolean.valueOf(false));
    dy = fhk.a(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", Boolean.valueOf(false));
    dz = fhk.a(0, "gads:request_pkg:enabled", Boolean.valueOf(true));
    bf = fhk.a(1, "gads:gmsg:disable_back_button:enabled", Boolean.valueOf(true));
    bg = fhk.a(0, "gads:gmsg:video_meta:enabled", Boolean.valueOf(true));
    dA = fhk.a(0, "gads:gmsg:video_meta:experiment_id");
    dB = fhk.a(1, "gads:network:cache_prediction_duration_s", 300L);
    bh = fhk.a(1, "gads:network:network_prediction_timeout_ms", 2000L);
    bi = fhk.a(0, "gads:mediation:dynamite_first:admobadapter", Boolean.valueOf(true));
    bj = fhk.a(0, "gads:mediation:dynamite_first:adurladapter", Boolean.valueOf(true));
    bk = fhk.a(1, "gads:bypass_adrequest_service_for_inlined_mediation", Boolean.valueOf(true));
    bl = fhk.a(0, "gads:resolve_future:default_timeout_ms", 30000L);
    bm = fhk.a(0, "gads:ad_loader:timeout_ms", 60000L);
    bn = fhk.a(0, "gads:rendering:timeout_ms", 60000L);
    bo = fhk.a(0, "gads:adshield:enable_adshield_instrumentation", Boolean.valueOf(false));
    bp = fhk.a(1, "gads:gestures:task_timeout", 2000L);
    bq = fhk.a(1, "gads:gestures:btt:enabled", Boolean.valueOf(false));
    br = fhk.a(1, "gads:gestures:sss:enabled", Boolean.valueOf(false));
    bs = fhk.a(1, "gads:gestures:asig:enabled", Boolean.valueOf(false));
    bt = fhk.a(1, "gads:gestures:tos:enabled", Boolean.valueOf(false));
    bu = fhk.a(1, "gads:gestures:ts", 1);
    bv = fhk.a(1, "gads:gestures:tdvs:enabled", Boolean.valueOf(false));
    bw = fhk.a(1, "gads:gestures:tvvs:enabled", Boolean.valueOf(false));
    bx = fhk.a(1, "gads:gestures:pk", "");
    by = fhk.a(1, "gads:gestures:bs:enabled", Boolean.valueOf(true));
    bz = fhk.a(1, "gads:gestures:check_initialization_thread:enabled", Boolean.valueOf(false));
    bA = fhk.a(1, "gads:gestures:get_query_in_non_ui_thread:enabled", Boolean.valueOf(true));
    bB = fhk.a(0, "gass:enabled", Boolean.valueOf(true));
    bC = fhk.a(0, "gass:enable_int_signal", Boolean.valueOf(true));
    bD = fhk.a(0, "gass:enable_ad_attestation_signal", Boolean.valueOf(true));
    dC = fhk.a(0, "gads:adid_notification:first_party_check:enabled", Boolean.valueOf(true));
    dD = fhk.a(0, "gads:edu_device_helper:enabled", Boolean.valueOf(true));
    bE = fhk.a(0, "gads:support_screen_shot", Boolean.valueOf(true));
    bF = fhk.a(0, "gads:use_get_drawing_cache_for_screenshot:enabled", Boolean.valueOf(true));
    dE = fhk.a(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
    dF = fhk.a(1, "gads:sdk_core_constants:experiment_id");
    bG = fhk.a(1, "gads:sdk_core_constants:caps", "");
    bH = fhk.a(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12L));
    bI = fhk.a(0, "gads:js_flags:mf", Boolean.valueOf(false));
    dG = fhk.a(1, "gads:js_flags:disable_phenotype", Boolean.valueOf(false));
    bJ = fhk.a(0, "gads:custom_render:ping_on_ad_rendered", Boolean.valueOf(false));
    bK = fhk.a(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    dH = fhk.a(0, "gads:native:engine_js_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/native_ads.js");
    dI = fhk.a(1, "gads:native:video_url", "//imasdk.googleapis.com/admob/sdkloader/native_video.html");
    bL = fhk.a(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
    dJ = fhk.a(1, "gads:singleton_webview_native:experiment_id");
    bM = fhk.a(1, "gads:enable_untrack_view_native", Boolean.valueOf(true));
    bN = fhk.a(1, "gads:ignore_untrack_view_google_native", Boolean.valueOf(true));
    bO = fhk.a(1, "gads:reset_listeners_preparead_native", Boolean.valueOf(true));
    bP = fhk.a(1, "gads:native_video_load_timeout", 10);
    bQ = fhk.a(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    bR = fhk.a(1, "gads:clamp_native_video_player_dimensions", Boolean.valueOf(true));
    bS = fhk.a(1, "gads:enable_store_active_view_state", Boolean.valueOf(false));
    bT = fhk.a(1, "gads:enable_singleton_broadcast_receiver", Boolean.valueOf(false));
    bU = fhk.a(1, "gads:native:overlay_new_fix:enabled", Boolean.valueOf(false));
    bV = fhk.a(1, "gads:native:count_impression_for_assets", Boolean.valueOf(false));
    bW = fhk.a(1, "gads:fluid_ad:use_wrap_content_height", Boolean.valueOf(false));
    bX = fhk.a(0, "gads:method_tracing:enabled", Boolean.valueOf(false));
    bY = fhk.a(0, "gads:method_tracing:duration_ms", 30000L);
    bZ = fhk.a(0, "gads:method_tracing:count", 5);
    ca = fhk.a(0, "gads:method_tracing:filesize", 134217728);
    dK = fhk.a(1, "gads:auto_location_for_coarse_permission", Boolean.valueOf(false));
    dL = fhk.b(1, "gads:auto_location_for_coarse_permission:experiment_id");
    cb = fhk.a(1, "gads:auto_location_timeout", 2000L);
    dM = fhk.b(1, "gads:auto_location_timeout:experiment_id");
    dN = fhk.a(1, "gads:auto_location_interval", -1L);
    dO = fhk.b(1, "gads:auto_location_interval:experiment_id");
    cc = fhk.a(1, "gads:fetch_app_settings_using_cld:enabled", Boolean.valueOf(false));
    dP = fhk.a(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
    cd = fhk.a(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000L);
    dQ = fhk.a(0, "gads:afs:csa:experiment_id");
    ce = fhk.a(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
    cf = fhk.a(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
    cg = fhk.a(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
    ch = fhk.a(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
    ci = fhk.a(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
    cj = fhk.a(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000L);
    dR = fhk.a(0, "gads:afs:csa_ad_manager_enabled", Boolean.valueOf(true));
    dS = fhk.a(1, "gads:parental_controls:send_from_client", Boolean.valueOf(true));
    dT = fhk.a(1, "gads:parental_controls:cache_results", Boolean.valueOf(true));
    ck = fhk.a(1, "gads:parental_controls:timeout", 2000L);
    dU = fhk.a(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
    dV = fhk.a(0, "gads:safe_browsing:safety_net:delay_ms", 2000L);
    cl = fhk.a(0, "gads:safe_browsing:debug", Boolean.valueOf(false));
    cm = fhk.a(0, "gads:webview_cookie:enabled", Boolean.valueOf(true));
    dW = fhk.a(1, "gads:cache:ad_request_timeout_millis", 250);
    dX = fhk.a(1, "gads:cache:max_concurrent_downloads", 10);
    dY = fhk.a(1, "gads:cache:javascript_timeout_millis", 5000L);
    cn = fhk.a(1, "gads:cache:bind_on_foreground", Boolean.valueOf(false));
    co = fhk.a(1, "gads:cache:bind_on_init", Boolean.valueOf(false));
    cp = fhk.a(1, "gads:cache:bind_on_request", Boolean.valueOf(false));
    cq = fhk.a(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30L));
    cr = fhk.a(1, "gads:cache:use_cache_data_source", Boolean.valueOf(false));
    dZ = fhk.a(1, "gads:cache:connection_per_read", Boolean.valueOf(false));
    ea = fhk.a(1, "gads:cache:connection_timeout", 5000L);
    eb = fhk.a(1, "gads:cache:read_only_connection_timeout", 5000L);
    cs = fhk.a(1, "gads:http_assets_cache:enabled", Boolean.valueOf(false));
    ct = fhk.a(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
    cu = fhk.a(1, "gads:http_assets_cache:time_out", 100);
    cv = fhk.a(1, "gads:chrome_custom_tabs:enabled", Boolean.valueOf(true));
    cw = fhk.a(1, "gads:chrome_custom_tabs_browser:enabled", Boolean.valueOf(false));
    cx = fhk.a(1, "gads:chrome_custom_tabs:disabled", Boolean.valueOf(false));
    cy = fhk.a(1, "gads:drx_in_app_preview:enabled", Boolean.valueOf(true));
    cz = fhk.a(1, "gads:drx_debug_signals:enabled", Boolean.valueOf(true));
    cA = fhk.a(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    cB = fhk.a(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    cC = fhk.a(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    cD = fhk.a(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    cE = fhk.a(1, "gads:drx_debug:timeout_ms", 5000);
    cF = fhk.a(1, "gad:pixel_dp_comparision_multiplier", 1);
    cG = fhk.a(1, "gad:interstitial_for_multi_window", Boolean.valueOf(false));
    cH = fhk.a(1, "gad:interstitial_ad_stay_active_in_multi_window", Boolean.valueOf(false));
    cI = fhk.a(1, "gad:interstitial:close_button_padding_dip", 0);
    cJ = fhk.a(1, "gads:clearcut_logging:enabled", Boolean.valueOf(false));
    cK = fhk.a(0, "gad:force_local_ad_request_service:enabled", Boolean.valueOf(false));
    cL = fhk.a(1, "gad:http_redirect_max_count:times", 8);
    ec = fhk.a(0, "gads:nonagon:red_button", Boolean.valueOf(false));
    ed = fhk.a(1, "gads:nonagon:banner:enabled", Boolean.valueOf(false));
    ee = fhk.a(1, "gads:nonagon:banner:ad_unit_exclusions", "(?!)");
    ef = fhk.a(1, "gads:nonagon:interstitial:enabled", Boolean.valueOf(false));
    eg = fhk.a(1, "gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
    eh = fhk.a(1, "gads:nonagon:rewardedvideo:enabled", Boolean.valueOf(false));
    ei = fhk.a(1, "gads:nonagon:mobile_ads_setting_manager:enabled", Boolean.valueOf(false));
    ej = fhk.a(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
    ek = fhk.a(1, "gads:nonagon:nativead:enabled", Boolean.valueOf(false));
    el = fhk.a(1, "gads:nonagon:nativead:ad_unit_exclusions", "(?!)");
    em = fhk.a(1, "gads:nonagon:service:enabled", Boolean.valueOf(false));
  }
  
  public static List<String> a()
  {
    return fex.e().a();
  }
  
  public static void a(Context paramContext)
  {
    dvy.a(paramContext, new fhw(paramContext));
    paramContext = dv;
    int i1 = ((Integer)fex.f().a(paramContext)).intValue();
    if ((i1 > 0) && (en == null)) {
      en = new byte[i1];
    }
  }
  
  public static void a(Context paramContext, int paramInt, JSONObject paramJSONObject)
  {
    fex.d();
    paramContext = paramContext.getSharedPreferences("google_ads_flags", 0).edit();
    fex.e().a(paramContext, 1, paramJSONObject);
    fex.d();
    paramContext.commit();
  }
  
  public static List<String> b()
  {
    return fex.e().b();
  }
}
